LangString addOrReinstall ${LANG_PORTUGUESEBR} "Reparar ou reinstalar"
LangString alreadyInstalled ${LANG_PORTUGUESEBR} "SLATE já instalado"
LangString alreadyInstalledLong ${LANG_PORTUGUESEBR} "O ${PRODUCTNAME} ${VERSION} já está neste computador. Escolha o que deseja fazer e clique em Avançar."
LangString appRunning ${LANG_PORTUGUESEBR} "O {{product_name}} está aberto. Feche a janela e tente novamente."
LangString appRunningOkKill ${LANG_PORTUGUESEBR} "O {{product_name}} precisa fechar para continuar.$\nClique em OK para fechá-lo com segurança."
LangString chooseMaintenanceOption ${LANG_PORTUGUESEBR} "Escolha como deseja cuidar desta instalação."
LangString choowHowToInstall ${LANG_PORTUGUESEBR} "Escolha onde deseja instalar o ${PRODUCTNAME}."
LangString createDesktop ${LANG_PORTUGUESEBR} "Criar atalho na área de trabalho"
LangString dontUninstall ${LANG_PORTUGUESEBR} "Manter a instalação atual"
LangString dontUninstallDowngrade ${LANG_PORTUGUESEBR} "Manter a instalação atual (uma versão anterior não pode substituí-la)"
LangString failedToKillApp ${LANG_PORTUGUESEBR} "Não foi possível fechar o {{product_name}}. Feche a janela e tente novamente."
LangString installingWebview2 ${LANG_PORTUGUESEBR} "Preparando o componente de interface do Windows…"
LangString newerVersionInstalled ${LANG_PORTUGUESEBR} "Este computador já tem uma versão mais nova do ${PRODUCTNAME}. Recomendamos manter a versão atual."
LangString older ${LANG_PORTUGUESEBR} "mais antiga"
LangString olderOrUnknownVersionInstalled ${LANG_PORTUGUESEBR} "Uma versão $R4 do ${PRODUCTNAME} já está instalada. Recomendamos removê-la antes de continuar."
LangString silentDowngrades ${LANG_PORTUGUESEBR} "A instalação silenciosa não substitui uma versão mais nova por uma mais antiga.$\n"
LangString unableToUninstall ${LANG_PORTUGUESEBR} "Não foi possível remover a instalação anterior."
LangString uninstallApp ${LANG_PORTUGUESEBR} "Remover o ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_PORTUGUESEBR} "Remover a versão atual antes de instalar"
LangString unknown ${LANG_PORTUGUESEBR} "desconhecida"
LangString webview2AbortError ${LANG_PORTUGUESEBR} "Não foi possível preparar o componente de interface do Windows. Reinicie o instalador."
LangString webview2DownloadError ${LANG_PORTUGUESEBR} "Não foi possível baixar o componente de interface do Windows: $0"
LangString webview2DownloadSuccess ${LANG_PORTUGUESEBR} "Componente de interface baixado."
LangString webview2Downloading ${LANG_PORTUGUESEBR} "Baixando o componente de interface do Windows…"
LangString webview2InstallError ${LANG_PORTUGUESEBR} "A preparação do componente de interface falhou com o código $1."
LangString webview2InstallSuccess ${LANG_PORTUGUESEBR} "Componente de interface pronto."
LangString deleteAppData ${LANG_PORTUGUESEBR} "Também apagar os dados locais e a identidade deste computador"
